### ISSUE TITLE
Stepman Share has a broken link

### ISSUE THREAD

**Issue by sudhanshuraheja** [bitrise-io/stepman#182]
Stepman share starts with the following, which isn't a valid link

To get started you can find a template Step repository at: https://github.com/bitrise-io/stepman/tree/master/_step_template

**Comment by viktorbenei** [comment]
Thanks, indeed we recently moved the template into a separate repository but forgot to update this link / text. Thanks for reporting! 😊

**Comment by sudhanshuraheja** [comment]
that was fast @viktorbenei :) thanks.

What is the new link for it?

**Comment by viktorbenei** [comment]
https://github.com/bitrise-steplib/step-template - I'll update the link right away! ;)
