### ISSUE TITLE
Include a license

### ISSUE THREAD

**Issue by jni-** [bitrise-io/stepman#186]
I wanted to install bitrise-cli, but while I'm at it I decided to make archlinux packages for envman, stepman and bitrise-cli. However, I can't publish this one since it has no license. Both envman and bitrise are under the MIT license.

I would have opened a PR, but it didn't seem right to "push" a license to your repo!

Thanks!

**Comment by viktorbenei** [comment]
Done, thanks for reporting! I'm not sure why/how it was left out, but it's now in place - MIT of course.

**Comment by viktorbenei** [comment]
btw if you have the packaging scripts/configs feel free to send a PR to include it in the repos. We plan to do that for Debian packages, as we mainly use Ubuntu, but we'd like to support more Linux distributions / package managers in the future

**Comment by jni-** [comment]
@viktorbenei thanks for the quick response! 

Here are the 3 packages : 
https://aur.archlinux.org/packages/envman/
https://aur.archlinux.org/packages/stepman/
https://aur.archlinux.org/packages/bitrise/

If you prefer, I can transfer ownership to you or someone on your team. AUR packages on arch are community-driven, so you are free to clone the AUR git repo and update it if you want. You can view the PKGBUILD on the right, which is all you need to create a package on arch. I'm no AUR expert though, so there might be room for improvement!

**Comment by viktorbenei** [comment]
I think it's better if you keep it for now, as we don't have anyone who could verify the updates. Although I looked at the PKGBUILD files and it seems trivial, but we don't mark/provide anything as "official" unless we can verify it.

That said, if you want to, feel free to add a section to the READMEs noting that an AUR package is available as an installation option.

Thanks again for your time & work!!
