### ISSUE TITLE
Short commands doesn't work

### ISSUE THREAD

**Issue by viktorbenei** [bitrise-io/stepman#189]
This:

```
stepman d -c https://github.com/bitrise-io/bitrise-steplib
FATA[19:34:06] [STEPMAN] - Missing step id
```

should be the same as this, but it's not:

```
stepman delete -c https://github.com/bitrise-io/bitrise-steplib
```

the second finished successfully

**Comment by godrei** [comment]
command alias `d` was duplicated (used for __download__ and __delete__ commands), so we removed every command alias (short command). Related PR: https://github.com/bitrise-io/stepman/pull/195/files
