### ISSUE TITLE
get spec.json of a specified collection

### ISSUE THREAD

**Issue by viktorbenei** [bitrise-io/stepman#191]
so that other tools can work with the spec.json directly, when required

**Comment by godrei** [comment]
stepman got a new command `export-spec` which you can use to export the specified StepLib spec. PR: https://github.com/bitrise-io/stepman/pull/197

**Comment by viktorbenei** [comment]
Lets try this again. `export-spec` is great, but we'd also need a `collection-path` or similar command, which does not export the spec into a new file, instead it prints the path of the collection/spec!

**Comment by viktorbenei** [comment]
Use case: a plugin which needs to read the spec.json of a collection, e.g. to list steps by a filter.

**Comment by godrei** [comment]
In the new stepman release, the `collections` command will print, the steplib's spec_path as well.

```
...
https://github.com/bitrise-io/bitrise-steplib
  spec_path: $HOME/.stepman/step_collections/1481200315/spec/spec.json
...
```
