### ISSUE TITLE
What's the difference between StepInfoModel.Source and StepInfoModel. SourceCodeURL ?

### ISSUE THREAD

**Issue by viktorbenei** [bitrise-io/stepman#205]
https://github.com/bitrise-io/stepman/blob/master/models/models.go#L133 & https://github.com/bitrise-io/stepman/blob/master/models/models.go#L135

Both are strings, and no comment around them.
What's the purpose of both here?
Please also add a comment for easier distinguishing ;)

**Comment by godrei** [comment]
Solved in: https://github.com/bitrise-io/stepman/pull/224
