### ISSUE TITLE
Retry spec download if fails

### ISSUE THREAD

**Issue by viktorbenei** [bitrise-io/stepman#206]
`stepman` should retry (with a short delay) the spec download (before falling back to a mirror/alternative source) if the first attempt fails, to improve reliability.

**Comment by jonasmaturana** [comment]
Just happened to me again. Two steps failed to download in the same build.

Have you considered fetching all steps before executing any of them? It it more frustrating to have a build fail after 10 minutes because of a service issue than if failed right away. Ideally it would never fail ;)

**Comment by viktorbenei** [comment]
I agree, but that should be implemented in the CLI - can you please create a GH issue there? https://github.com/bitrise-io/bitrise/issues

**Comment by viktorbenei** [comment]
Another thing we're thinking about was a mechanism to "vendor" the steps into your code repository.

**Comment by viktorbenei** [comment]
Related PR: https://github.com/bitrise-io/stepman/pull/210

**Comment by viktorbenei** [comment]
PR merged, will be part of the next `stepman` / Bitrise CLI release (scheduled for next week)!

Thanks for reporting the issue, and feel free to create a new one for pre-fetching all steps before the build 🚀
